spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  issuer: jwt-practice
  secretKey: "A3q9mT5xV2c7L0pZ8rN1wS4yH6kJ2uQ9dR5fG1tE7bC3mN0pL2vX8zQ4sD6fH9"
  access-exp-min: 15
  refresh-exp-days: 14